wmde/new-lexeme-special-page

README.md

This is a very basic stub to be extended as we setup the dev environment.
Bug: T300883

Add README.md stub

---

package.json

This should unlock of the follow-up tasks
Bug: T300883

Add package.json to allow adding dependencies

---

.husky/pre-commit
.prettierignore
.prettierrc.js
package-lock.json
package.json

This adds basic linting to yaml and json files.
As discussed, the pre-commit hook only checks files, it does not write anything. There is a `npm` script for that though.
Bug: T300893

Add husky setup and first pre-commit hook

---

index.html
package-lock.json
package.json
src/App.vue
src/components/HelloWorld.vue
src/env.d.ts
src/main.ts
tsconfig.json
vite.config.ts

Based on `npm init vite@latest -- --template vue-ts`, somewhat edited.
Bug: T300884

Set up Vite, Vue 3 and TypeScript

---

.eslintrc.js
package-lock.json
package.json
src/App.vue
src/components/HelloWorld.vue
src/env.d.ts

This also sets up scripts to fix these files and automatic linting in a pre-commit hook.
Bug: T300889

Lint js, ts and vue files

---

jest.config.js
jest.overrides.js
package-lock.json
package.json
src/components/HelloWorld.vue
tests/unit/HelloWorld.test.ts
tsconfig.json

The test currently imports the local component with a relative link
instead of an alias because of [T301267](https://phabricator.wikimedia.org/T301267).
Co-authored-by: Lucas Werkmeister <lucas.werkmeister@wikimedia.de>
Bug: [T300890](https://phabricator.wikimedia.org/T300890)

Add jest scaffolding

---

index.html
src/App.vue
src/main.ts
vite.config.ts

See commit messages. (Could also be split into several PRs, not sure.)

Prepare integration with WikibaseLexeme

---

package-lock.json
package.json
src/components/HelloWorld.vue
src/main.ts
src/store/RootState.ts
src/store/actions.ts
src/store/index.ts
src/store/mutations.ts
tests/unit/HelloWorld.test.ts
vite.config.ts

This change sets up Vuex alongside a demo implementation, which utilizes the preferred vuex project directory structure.
Bug: [T300886](https://phabricator.wikimedia.org/T300886)

Setup Vuex

---

package-lock.json
package.json

With this we can use a more recent version of postcss that is no longer vulnerable and that yellow bar should go away.

Upgrade stylelint-config-wikimedia to resolve vuln notification

---

.eslintrc.js
src/App.vue

With kebab-case for now, by current majority opinion.

Lint for consistent component casing

---

src/App.vue
vite.config.ts

This creates the basic layout of the special page in context of creating the basic form for T301234.
The message component is currently just a placeholder. When work on that message properly, we'll extract it into a separate component.

Layout for the form in context of the special page

---

src/components/LemmaInput.vue
src/components/LexicalCategoryInput.vue
tests/integration/NewLexemeForm.test.ts

Replace leftover mw-snl-* classes with just snl-*

---

jest.config.js
package-lock.json
package.json
src/components/LanguageInput.vue
src/components/LemmaInput.vue
src/components/LexicalCategoryInput.vue
src/components/NewLexemeForm.vue
vite.config.ts

It would be good to check that it still works in mediawiki as expected with the overall vite compatibility config set to 3.

Use native Vue 3 Wikit

---

cypress/integration/NewLexemeForm.spec.js
index.html
src/@types/mediawiki.ts
src/components/NewLexemeForm.vue
src/data-access/AlertLexemeCreator.ts
src/data-access/LexemeCreator.ts
src/init.ts
src/main.ts
src/mediawiki/MwApiLexemeCreator.ts
src/store/actions.ts
src/store/index.ts
tests/integration/NewLexemeForm.test.ts
tests/mocks/unusedLexemeCreator.ts
tests/unit/main.test.ts
tests/unit/mediawiki/MwApiLexemeCreator.test.ts
tests/unit/store/actions.test.ts

- Introduce the LexemeCreator Interface implement it in the MwApiLexemeCreator
- Adjust Store, add relevant action
- Integration and unit tests
Bug: [T302961](https://phabricator.wikimedia.org/T302961)

Create Lexemes using the API

---

index.html
src/@types/mediawiki.ts
src/data-access/DevItemSearcher.ts
src/data-access/ItemSearcher.ts
src/data-access/MwApiItemSearcher.ts
src/data-access/apiBasedItemSearcher.ts
src/init.ts
src/main.ts
src/plugins/ItemSearchPlugin/ItemSearch.ts
tests/mocks/unusedApi.ts
tests/mocks/unusedItemSearcher.ts
tests/unit/data-access/MwApiItemSearcher.test.ts
tests/unit/data-access/MwApiLexemeCreator.test.ts
tests/unit/main.test.ts

This can be used as a basis for the lookups (#78).
----
TODO:

Prepare for searching items

---

src/components/WikitLookup.ts

Add missing compatConfig to WikitLookup

---

cypress/integration/NewLexemeForm.spec.js
src/components/LexicalCategoryInput.vue
tests/integration/NewLexemeForm.test.ts

The main chunk of the work for this was done in #78 for T298139. Now
we're reaping the benefits by being able to reuse all that code.
Bug: T298149

Use lookup for lexical category

---

src/components/ErrorMessage.vue
src/components/NewLexemeForm.vue
src/data-access/DevLexemeCreator.ts
src/data-access/MwApiLexemeCreator.ts
src/store/RootState.ts
src/store/actions.ts
src/store/index.ts
src/store/mutations.ts
tests/unit/store/mutations.test.ts

- Create an ErrorMessage component to be used in the New Lexeme Form
- Add errors to the store 
- Add correspondent actions and mutations
- set up DevLexemeCreator to display an error at will
Bug: T304490

Error message display

---

tests/unit/store/actions.test.ts

The first test for the `CREATE_LEXEME` action was logging an error to the console (though that doesn’t make the test fail), complaining about the `CLEAR_ERRORS` mutation being missing. Fix that, and also add another test checking that the action clears and adds errors as expected.
The new test includes this line of code:
```js
await expect( store.dispatch( CREATE_LEXEME ) ).rejects.toBe( null );
```
In my opinion, we shouldn’t actually care about *what* the promise rejects with – however, `await expects( … ).rejects;` on its own doesn’t work: you have to perform some match on the rejected value, otherwise it counts as an unhandled promise rejection. I couldn’t find a “just accept anything” matcher that works here, so let’s just assert null, I guess.

Avoid console.error() in test and add extra test

---

index.html
src/components/NewLexemeForm.vue
src/components/SpellingVariantInput.vue
src/plugins/MessagesPlugin/DevMessagesRepository.ts
src/plugins/MessagesPlugin/MessageKeys.ts
src/store/RootState.ts
src/store/index.ts
src/store/mutations.ts
tests/integration/NewLexemeForm.test.ts
tests/unit/components/SpellingVariantInput.test.ts

Create the spelling variant lookup field

---

cypress/integration/NewLexemeForm.spec.js
src/store/actions.ts
tests/integration/NewLexemeForm.test.ts
tests/unit/store/actions.test.ts

Use new Spelling Variant Lookup when creating new Lexeme

---

cypress/integration/NewLexemeForm.spec.js

Add&Adjust Cypress tests for language code inference

---

README.md
package.json

Remove deployCommit command and relevant README section

---

README.md

Split it into the one-time setup and the day-to-day work, and provide some more details on both.
Bug: T302321

Expand local development section of README.md

---

index.html
src/@types/mediawiki.ts
src/data-access/tracking/MwTracker.ts
src/data-access/tracking/Tracker.ts
src/init.ts
src/main.ts
src/store/actions.ts
src/store/index.ts
tests/integration/App.test.ts
tests/integration/NewLexemeForm.test.ts
tests/mocks/unusedTracker.ts
tests/unit/main.test.ts
tests/unit/services/Tracker/MwTracker.test.ts
tests/unit/store/actions.test.ts

The MwTrack type is based on the [MediaWiki core documentation][1] as well as the [statsv documentation][2].
[1]: https://doc.wikimedia.org/mediawiki-core/master/js/#!/api/mw-method-track
[2]: https://wikitech.wikimedia.org/wiki/Graphite#statsv
Bug: T303394

Introduce Tracker service and track Lexeme creations

---

package-lock.json
package.json
tsconfig.json

Can't update jest and ts-jest yet, because @vue/vue3-jest depends on jest 27.

Update deps and change module type in tsconfig to commonjs

---

index.html
src/components/ItemLookup.vue
src/components/LexicalCategoryInput.vue
src/plugins/ConfigPlugin/Config.ts
tests/integration/App.test.ts
tests/integration/NewLexemeForm.test.ts
tests/unit/main.test.ts

also adds a manual list to index.html for the
dev entrypoint
Bug: T298150

Add lexicalCategorySuggestions to Config and to the ItemLookup

---

README.md

Expand Readme sections on linting and testing

---

src/components/ItemLookup.vue

See the individual commit messages; I think it makes sense to have this as one pull request, but merge it as ~~two~~ three separate commits (merge with rebase).
The refactoring also prepares for further changes to the `ItemLookup` that will be made in T308118.

Refactor ItemLookup to fix two minor suggestion-related bugs

---

package-lock.json
package.json

This pulls in a fix for disabled buttons, among other things.
Bug: T304511

Update Wikit packages to 3.0.0-alpha.3

---

src/components/LemmaInput.vue
src/components/NewLexemeForm.vue
src/plugins/MessagesPlugin/DevMessagesRepository.ts
src/plugins/MessagesPlugin/MessageKeys.ts
src/store/RootState.ts
src/store/actions.ts
src/store/index.ts
src/store/mutations.ts
tests/integration/NewLexemeForm.test.ts
tests/unit/components/LemmaInput.test.ts
tests/unit/store/actions.test.ts

This is the second PR split out of #192 and building on top of #198. It includes an entire vertical slice of the functionality

Show error if Lemma is missing

---

src/components/LexicalCategoryInput.vue
src/components/NewLexemeForm.vue
src/plugins/MessagesPlugin/DevMessagesRepository.ts
src/plugins/MessagesPlugin/MessageKeys.ts
src/store/RootState.ts
src/store/actions.ts
src/store/index.ts
tests/unit/store/actions.test.ts

This targets #199 and has been split out of #192

Show error if lexical category is missing at submit

---

src/components/LanguageInput.vue
src/components/NewLexemeForm.vue
src/plugins/MessagesPlugin/DevMessagesRepository.ts
src/plugins/MessagesPlugin/MessageKeys.ts
src/store/RootState.ts
src/store/actions.ts
src/store/index.ts
tests/unit/store/actions.test.ts

Show error if language is missing

---

src/components/NewLexemeForm.vue
src/components/SpellingVariantInput.vue
src/plugins/MessagesPlugin/DevMessagesRepository.ts
src/plugins/MessagesPlugin/MessageKeys.ts
src/store/RootState.ts
src/store/actions.ts
src/store/index.ts
tests/unit/components/SpellingVariantInput.test.ts
tests/unit/store/actions.test.ts

Show error of missing spelling variant

---

src/components/NewLexemeForm.vue

That setter became unused in #130 / 003c8e7

Clean up unused setter and simplify getter

---

src/components/LemmaInput.vue
src/plugins/ConfigPlugin/Config.ts
src/plugins/MessagesPlugin/DevMessagesRepository.ts
src/plugins/MessagesPlugin/MessageKeys.ts
tests/integration/App.test.ts
tests/integration/NewLexemeForm.test.ts
tests/unit/components/LemmaInput.test.ts
tests/unit/main.test.ts

add messages to the Message plugin
add maxLemmaLength to the Config plugin
use to validate input length and display error inline
Bug: T308654

Validate Lemma input length

---

package-lock.json
package.json

This improves the Enter key behavior of the Lookup component.
Bug: T305359

Update Wikit packages to 3.0.0-alpha.4

---

src/components/LemmaInput.vue

Pass maximum lemma length into message

---

tests/unit/components/LemmaInput.test.ts

Restructure createComponent() so that it’s possible to usefully override the `provide` globals as well, and use that to inject a custom messages plugin implementation.
Bug: T308654

Test that max lemma length is passed into message

---

package-lock.json
package.json

This introduces a Link component and improves accessibility of the Lookup component.

Update Wikit packages to 3.0.0-alpha.6

---

src/components/SpellingVariantInput.vue

Bug: [T312292](https://phabricator.wikimedia.org/T312292)

Open spelling variant help link in new tab

---

package-lock.json
package.json

Bug: [T313744](https://phabricator.wikimedia.org/T313744)

Update vite to version 3.0.1

---

package-lock.json
package.json

Bug: [T312633](https://phabricator.wikimedia.org/T312633)

Install new version of wikit v.3.0.0-alpha.8

---

package-lock.json
package.json

Bug: [T315964](https://phabricator.wikimedia.org/T315964)

Update vite related packages

---

README.md

Partially based on the task descriptions of T313744 and T311696.
Bug: T311696

Document chore procedure in README

---

package-lock.json
package.json

```sh
npm i {stylelint{,-config-standard-scss},@namics/stylelint-bem}@latest
```
Bug: T322121

Update Stylelint-related dependencies

---

src/plugins/MessagesPlugin/DevMessagesRepository.ts

Update lemma help link target URL

---

README.md
package-lock.json
package.json

Also, this updated Vite to the latest patch version.

Add line about not updating Vite to v3 to README

---

package-lock.json
package.json

```bash
npm i @wmde/wikit-{tokens,vue-components}@3.0.0-alpha.9
```
Bug: T323899

Update Wikit-related dependencies

---

package-lock.json
package.json

Bug: [T324743](https://phabricator.wikimedia.org/T324743)

Install wikit v3.0.0-alpha.10

---

package-lock.json
package.json

`npm install @vue/test-utils vue-tsc`
Bug: T326199

Update Vue-related dependencies (but Vue(x) itself)

---

package-lock.json
package.json

This should fix an accessibility issue axe-core 4.6 complained about.
Bug: T326681

Update Wikit to v3.0.0-alpha.11

---

package-lock.json
package.json

With Wikit v3.0.0-alpha.11, this should work now.
Bug: T326681

Update axe-core to v4.6.2

---

package-lock.json
package.json

Bug: [T335735](https://phabricator.wikimedia.org/T335735)

Update @rushstack/eslint-patch dependencies

---

package-lock.json
package.json

Bug: [T335735](https://phabricator.wikimedia.org/T335735)

Update Sass dependencies

---

package-lock.json
package.json

Bug: [T325822](https://phabricator.wikimedia.org/T325822)

Upgrade wikit version

---

README.md

Language is especially hard today, happy for any suggestions on how to phrase things better.

Be more explicit about instruction for deploying changes

---

package-lock.json
package.json

```bash
npm i @types/{jest,lodash}@latest
```
Bug: T350664

Update @types/* packages

---

package-lock.json
package.json

Minor updates to vite-related packages. Backports and dependencies mostly
Bug: T354166

Upgrade vite and @vitejs/plugin-vue

---

package-lock.json
package.json

Minor updates to the typescript and @types/jest packages.
Bug: T356273

Upgrade typescript and @types/jest

---

src/components/ItemLookup.vue

Enable bold labels in item lookup
