wmde/new-lexeme-special-page

.editorconfig
.github/dependabot.yml
package.json

This is basically a follow-up to #4. Some form of linting for this will be added in the next PR.

Use tabs to indent yaml and json files

---

package-lock.json
package.json
src/App.vue
src/components/HelloWorld.vue
vite.config.ts

Use the migration build, mapping not only `vue` but also `@vue/composition-api` (used by Wikit) to `@vue/compat`. For `@click.native` to work, we need `MODE: 2` in the Vite config, or at least I haven’t yet found a way to make it work in `MODE: 3`. At some point, we’re hoping to have a properly Vue 3-compatible (subset of) Wikit, so that we can drop the migration build and use Vue 3 alone.
Bug: T301145

Set up Wikit (vue3compat build)

---

.eslintrc.js
vite.config.ts

These were accidentally introduced in #9, which was merged after linting had been added in the meantime.
In vite.config.js, reconfigure the quote-props lint to “consistent as needed” mode, because I don’t think it makes sense to unquote only the “vue” prop of the alias config.

Fix lint errors

---

README.md

This change adds a bare-bones dev instructions to our documentation, mainly as a way to test mirroring with phabricator diffusion.
Bug: [T301335](https://phabricator.wikimedia.org/T301335)

Add rudimentary dev instructions

---

vite.config.ts

It’s already in some of our other configs, but still missing here.
Co-Authored-By: Michael Große <michael.grosse@wikimedia.de>

Add @/ alias to vite.config.ts

---

tsconfig.json

Following the Codex design system, which probably targets the same set of browsers we target, and which we want to use at some point anyways.

Change esnext to es2015

---

tests/mocks/styleMock.js

It’s already referenced in jest.config.js, but didn’t exist yet. This didn’t come up before because we didn’t have a test pulling in `App.vue` yet, but we’ll want such a test at some point.

Add missing styleMock.js file

---

.eslintrc.js
package-lock.json
package.json

It’s not correctly understanding our imports yet, producing unwanted errors, and even if we put in the time to configure it correctly, its usefulness seems dubious at best. (If we really have broken imports, we’d probably find out about it during the build or test steps.) Let’s just remove it.

Stop using eslint-plugin-import

---

package.json
vite.config.ts

Netlify actually needs an index.html in the dist directory. However this
is not added for a library build. So this creates an extra build command
to keep building it as an app that makes still use of the index.html,
link `npm run dev`. This skips the type checking as the build currently
runs on Netlify itself and there we only have a limited amount of build
minutes included. Rather the type checking should be part of the "code
quality" CI job.
This Netlify hosting was broken in #19 / 171d33f
This would allow devtools to work, but might in theory have slight differences
to production?

fix Netlify hosting

---

src/components/HelloWorld.vue
src/main.ts
src/plugins/MessagesPlugin/MessageKeys.ts
src/plugins/MessagesPlugin/Messages.ts
src/plugins/MessagesPlugin/MessagesRepository.ts
tests/unit/plugins/Messages.test.ts

In the compositionApi we cannot access `this`, so using a global instance method does not work. The established way to deal with this in Vue 3 is to use provide/inject.
Using provide/inject works well, with the one exception that requires a fallback or will be typed `Messages|undefined`. This leaves a couple of non-ideal solutions:
1. assert it as non-null it with `!`
2. cast it with `as Messages`
3. have some if-guard that throws an Error
4. Provide a simple fallback
I went with option 4 and extended the original Messages class from [Data Bridge] with a fallback if no repository is provided. This also makes the initialization in the index.html easier and still allows for a more elaborate mock in the future, if we want it.
[Data Bridge]: …

Add i18n plugin

---

src/components/LexicalCategoryInput.vue
src/components/NewLexemeForm.vue
src/plugins/MessagesPlugin/MessageKeys.ts
src/store/RootState.ts
src/store/actions.ts
src/store/index.ts
src/store/mutations.ts
tests/integration/NewLexemeForm.test.ts

Just a plain text field for now, the proper lookup will come later.
Also, add `await` in the integration test, my IDE tells me `setValue()` should be awaited (though the tests seem to work without it).
Bug: T301783

Add basic input for lexical category

---

.stylelintrc.json
src/components/NewLexemeForm.vue

This change adds a linting rule based on the rule that was proposed in Mattermost and the discussion the ensued. It is related to our first HTML and CSS setup and the stylelint setup task.
Bug: [T301234](https://phabricator.wikimedia.org/T301234)
Bug: [T300888](https://phabricator.wikimedia.org/T300888)

Enforce class prefixes

---

src/components/NewLexemeForm.vue
src/store/actions.ts

The actions aren’t worth the overhead here. Leave some commented-out guidance behind in `actions.ts`, because we’ll surely want some actions again at some point.

Directly use mutations in NewLexemeForm

---

src/components/LanguageInput.vue
src/components/NewLexemeForm.vue
src/plugins/MessagesPlugin/MessageKeys.ts
src/store/RootState.ts
src/store/index.ts
src/store/mutations.ts
tests/integration/NewLexemeForm.test.ts

Just a plain text field for now, the proper lookup will come later.
Bug: T301894
---
~~This kind of incorporates #41, in that it uses mutations without actions. It would probably be best to merge #41 and then rebase this.~~ Rebased.

Add basic input for language

---

vite.config.ts

Apparently this doesn’t actually need a `resolve()` call, it can just resolve to itself (just like `Typography` below) and that’s enough to exempt it from the overall `@wmde/wikit-vue-components` alias.

Simplify wikit-vue-components CSS alias in vite.config.ts

---

src/main.ts
src/store/index.ts
tests/integration/NewLexemeForm.test.ts

Instead of directly exporting a store instance, export a function to create the store, which can pass through some initial state. In this commit, we’re not actually defining any such state yet, but that will come soon, so we already use the interface / object-destructure syntax and temporarily silence the lints complaining about that.
Co-Authored-By: Noa wmde <noa.rave@wikimedia.de>
Co-Authored-By: Itamar Givon <itamar.givon@wikimedia.de>
---
Extracted from #47, since we’ll also want it for the [CSRF token](https://phabricator.wikimedia.org/T302001).

Allow passing state from createAndMount to store

---

src/components/NewLexemeForm.vue
src/main.ts
src/store/RootState.ts
src/store/index.ts
tests/integration/NewLexemeForm.test.ts
tests/unit/main.test.ts

Using a token passed into `createAndMount()`.
Bug: T302001
---
This doesn’t include a test for `createAndMount` passing the token into the store, because I’m not sure how to test that. Should we test (again) that there’s an input with the right value? (But then `main.test.ts` probably belongs in `integration/` rather than `unit/`.)

Add hidden token input to form

---

package.json

This command doesn’t actually contribute to the build results, it just takes a lot of time (much longer than `vite build` itself). We already run this as part of the test command, so I don’t think there’s a reason to keep it in the build command as well.

Remove vue-tsc from build command

---

cypress.json
cypress/integration/NewLexemeForm.spec.js
package-lock.json
package.json
src/components/NewLexemeForm.vue

This is a temporary solution to make creating lexemes work, by targeting the noscript backend of the special page; we want to replace this with an API request later. (At some point the hard-coded lemma-language will also be replaced, of course.)
The previous simple Cypress test is replaced with one that watches for a form submit and checks the submitted data (including a token that we hard-code in index.html). Unfortunately, Chromium reports inexplicable cross-origin errors when submitting, blocking the iframe with origin http://localhost:3000 from accessing a cross-origin frame at http://localhost:3000, or something like that (yes, that’s the same host twice, as far as I can tell). I haven’t been able to find a solution for that, so for now, work around it by disabling Chrome web …

Add lemma language input and submit form

---

src/components/NewLexemeForm.vue
src/main.ts
src/plugins/MessagesPlugin/MessageKeys.ts
src/plugins/MessagesPlugin/MockMessagesRepository.ts
src/store/RootState.ts
src/store/index.ts
tests/integration/NewLexemeForm.test.ts

While working on this it became apparent we are going to have to get some of the information from the RepoSettings in order to display the CC0 license link correctly. 
This PR reflects the new-lexeme-special-page side of receiving the parameters, initiating the store with them and using them within the component.
Bug: [T298152](https://phabricator.wikimedia.org/T298152)

Add licensing information

---

package-lock.json
package.json

Avoids warnings of this sort:
> WARNING: You are currently running a version of TypeScript which is
> not officially supported by @typescript-eslint/typescript-estree.
>
> You may find that it works just fine, or you may not.
>
> SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.6.0
>
> YOUR TYPESCRIPT VERSION: 4.6.2

Update typescript-eslint packages

---

index.html
src/init.ts
src/main.ts
tests/unit/main.test.ts

We’ll need more than one service soon, so let’s turn this into a container of possibly several services. The `messagesRepository` service remains optional for now, but the whole `services` object is required, even if it’s just the empty object. (I’m not yet sure if additional services will also be optional or required.)
Bug: T302961

Turn second createAndMount() param into services object

---

src/components/LanguageInput.vue
src/components/LemmaInput.vue
src/components/LexicalCategoryInput.vue
src/components/NewLexemeForm.vue

It turns out we still need those while running under the migration build.

Add back compatConfig blocks

---

index.html
src/components/NewLexemeForm.vue
src/main.ts
src/store/RootState.ts
src/store/index.ts
tests/integration/NewLexemeForm.test.ts
tests/unit/main.test.ts

No longer needed now that we’re using the API to create lexemes, `postWithEditToken()` adds the token automatically.
Bug: T302961

Remove hidden token input from NewLexemeForm

---

src/init.ts

`init()` now expects tags as part of its config, which are used when creating a new lexeme.
Bug: T302961
---
WikibaseLexeme counterpart: https://gerrit.wikimedia.org/r/c/mediawiki/extensions/WikibaseLexeme/+/771371

Pass tags into MwApiLexemeCreator

---

src/@types/mediawiki.ts
src/init.ts

We want to make sure that the API uses the current user interface language, even if that was only set via `?uselang=` and isn’t in the user’s session, and also want to use the modern result format. Also, let’s set the error format already, though for now this is mostly a guess since we haven’t implemented error handling yet.

Add default parameters to mw.Api()

---

src/components/ItemLookup.vue
src/components/LanguageInput.vue
src/components/LemmaInput.vue
src/components/LexicalCategoryInput.vue
src/components/NewLexemeForm.vue
src/plugins/MessagesPlugin/DevMessagesRepository.ts

Vue escapes by default the text it displays, therefore we must not give it already escaped text.
The dev message repository has been adjusted to better mimic what the mediawiki mw.messages API does.

Fix double escape

---

index.html
src/components/NewLexemeForm.vue
src/init.ts
src/main.ts
src/plugins/ConfigPlugin/Config.ts
src/store/RootState.ts
src/store/index.ts
tests/integration/NewLexemeForm.test.ts
tests/unit/main.test.ts

The config isn’t mutable state, so it doesn’t really belong in the store. A plugin that components can use directly seems to make more sense. (Mark the members of the new `Config` interface `readonly` to highlight that they’re not mutable.)
Bug: T303050

Move config from store to plugin

---

src/components/NewLexemeForm.vue
src/plugins/MessagesPlugin/DevMessagesRepository.ts
src/plugins/MessagesPlugin/MessageKeys.ts

This adds the `wikibaselexeme-newlexeme-submit-error `message key to the message repository and uses it in `NewLexemeForm.vue`.
Bug: T304490

add submit error message to Message pipeline and the Form component

---

.stylelintrc.json
package-lock.json
package.json

This effectively extends the functionality of the selector-class-pattern
rule, and so that rule can be dropped from the configuration.
From the other rule-sets mentioned in T301694,
stylelint-selector-bem-pattern has much more complex configuration for
little apparent benefit. And Vue-BEM adds a new custom directive that
also seems like too much complexity for what little of a problem we here
have.
Thus, this uses https://github.com/merkle-open/stylelint-bem
Bug: T301694

Add linting for BEM-style classes in scss

---

src/data-access/LangCodeRetriever.ts
src/data-access/apiBasedLangCodeRetriever.ts
tests/unit/data-access/MwApiLangCodeRetriever.test.ts

Somevalue should be treated like an error, but novalue can be considered equivalent to a missing statement for our purposes (i.e. shows no warning message).
Bug: T305542

Treat novalue like missing statement in LangCodeRetriever

---

src/data-access/LanguageCodesProvider.ts
src/main.ts
tests/mocks/unusedLanguageCodesProvider.ts
tests/unit/data-access/LangCodeProvider.test.ts

We didn’t think we needed this initially, but in the tests it’s very annoying when TypeScript complains about the missing private property validLanguageCodes for every fake implementation.
Bug: T305542
Co-Authored-By: Michael Große <michael.grosse@wikimedia.de>

Extract LanguageCodesProvider interface

---

src/components/NewLexemeForm.vue
src/components/SpellingVariantInput.vue
src/main.ts
src/store/RootState.ts
src/store/actions.ts
src/store/index.ts
src/store/mutations.ts
tests/integration/NewLexemeForm.test.ts
tests/unit/store/actions.test.ts

Todo:
Cypress test will be updated in a separate commit. (In this commit, it probably asks for the language code of [September (Q123)](https://www.wikidata.org/wiki/Q123), which isn’t very nice but doesn’t need to block merging this.) Showing a warning will also be done separately.
Bug: T305542

Create Action to infer LanguageCode

---

src/components/ItemLookup.vue
src/components/LanguageInput.vue
src/plugins/MessagesPlugin/DevMessagesRepository.ts
src/plugins/MessagesPlugin/MessageKeys.ts
tests/integration/NewLexemeForm.test.ts

If there is a language code statement on the language item (including a somevalue statement, but not a novalue statement), but its value is not a valid language code, show a warning message to the user.
Bug: T305542

Add warning message for invalid language code

---

src/data-access/LangCodeRetriever.ts
src/data-access/MwApiLangCodeRetriever.ts

Especially in CI, there can be no language code property configured. The
app should still work in that case.
Bug: T306170

Don't crash if no languageCodeProperty configured

---

src/components/NewLexemeForm.vue
tests/integration/NewLexemeForm.test.ts

This if-wrapper was probably just left over from development, but we
also want to remove the selected language value from the store when it
is deselected in the Lookup.

Always handle change in the Language input

---

src/plugins/MessagesPlugin/DevMessagesRepository.ts

This is mimics what `mw.msg` does. It is needed for testing the
filtering based on the replaced message in the spelling variant options.

Replace parameters in Dev messages

---

index.html
src/components/SpellingVariantInput.vue
src/data-access/LanguageCodesProvider.ts
src/main.ts
src/plugins/ConfigPlugin/Config.ts
src/plugins/MessagesPlugin/DevMessagesRepository.ts
src/plugins/MessagesPlugin/MessageKeys.ts
tests/integration/NewLexemeForm.test.ts
tests/mocks/unusedLanguageCodesProvider.ts
tests/unit/components/SpellingVariantInput.test.ts
tests/unit/data-access/LangCodeProvider.test.ts
tests/unit/main.test.ts
tests/unit/store/actions.test.ts

Show and Filter Language Names in Spelling Variant Lookup

---

index.html
src/plugins/MessagesPlugin/DevMessagesRepository.ts

With #143 the dev message looks now a bit less nice in the dev/staging page because the `{` is double escaped rather than parsed. This fixes this by replacing it with a value that would plausibly be provided by `mw.msg` as well.

Nicer copyright message in Dev/Staging view

---

src/plugins/MessagesPlugin/DevMessagesRepository.ts
tests/integration/NewLexemeForm.test.ts

The messages themselves are hard-coded, we know they’re safe; this way, we can also make the links in the shortcopyrightwarning message work.
This means that the NewLexemeForm integration tests now need to supply a full config, otherwise `undefined` ends up being passed into the messages plugin, where it now causes an error.

Don’t escape dev messages, only arguments

---

.github/workflows/code-quality.yaml
README.md
package-lock.json
package.json

As far as I can tell, the history of the Node requirement so far was:
1. bc365a6229 (#10): CI is added, running on Node 16 (then-current LTS); .nvmrc=16 is added at the same time, presumably for consistency
2. c2aa5b7773 (#16): Node 16 added to README, presumably based on .nvmrc
3. e0c53b713d (#55): Node 16 added to package.json, based on .nvmrc
So the Node version requirement gradually, and I think unintentionally, mutated from “let’s run CI on the latest software” into “we *need* the latest software”. But a full `npm cit` run still works under Node 14, and I think there is some value to supporting this version as well, as it’s currently the latest Node version supported by [Fresh][1]. So let’s change most of the Node 16 requirements to Node 14 instead.
However, we do need npm v7 or …

Mostly downgrade required Node version from 16 to 14

---

src/components/ItemLookup.vue

As far as I can tell, debouncedSearchForItems doesn’t need to be a ref, and I didn’t find any explanation for this in the comments of #78 either. Let’s try simplifying it…

Simplify ItemLookup code a bit

---

src/data-access/DevItemSearcher.ts
src/data-access/MwApiItemSearcher.ts
src/data-access/apiBasedItemSearcher.ts
tests/unit/data-access/MwApiItemSearcher.test.ts

We don’t need to support old Wikibase versions, so now that the patches for T104344 have been merged for a few weeks, it should be fine to use the display field instead of the label and description fields. (Note that the display field is guaranteed to be present even when empty since wikimedia/Wikibase@4fec51a6b8 / change I2de40f965a), so one test case that was omitting it needs to be updated.)

Use new display section of wbsearchentities response

---

src/components/ItemLookup.vue
src/data-access/DevItemSearcher.ts
src/data-access/ItemSearcher.ts
src/data-access/apiBasedItemSearcher.ts
tests/unit/components/ItemLookup.test.ts
tests/unit/data-access/MwApiItemSearcher.test.ts

This makes SearchedItemOption usable as type for
the lexical category search suggestions from php.
Bug: T298150

Rename SearchedItemOption.itemId to id

---

src/components/ItemLookup.vue
src/components/LanguageInput.vue

This seems to work better with eslint once we start using `withDefaults` (#176); with the previous code, `vue/require-default-prop` complains that “Prop 'error' requires default value to be set”.

Change ItemLookup error prop from optional to nullable

---

src/components/ItemLookup.vue
tests/unit/components/ItemLookup.test.ts

Show the matching suggested items as soon as possible, and prepend them to the search results, taking care not to repeat the items in the search results.
In this implementation, if the search results contain an item that is in the suggestions but was not matched by its label in the suggestions (e.g. an alias, or a label in another language), then that item will be ordered among the search results, not among the suggested items.
Bug: T298150

Show suggested lexical categories in lookup

---

cypress.json

No longer needed now that we don’t submit the form anymore.
This partially reverts commit e0c53b713d97eb17a7308861355692babbd63f7d.
Bug: T302961

Remove chromeWebSecurity: false from cypress.json

---

.eslintrc.js
package-lock.json
package.json

This doesn’t find any issues at the moment, but I’ve checked that it does something (if you add an `<img>` element without `alt=` attribute, it complains).
Bug: T307912

Add eslint-plugin-vuejs-accessibility

---

src/components/ItemLookup.vue

This function doesn’t do anything asynchronously. (It *calls* an async function, debouncedSearchForItems, but doesn’t await it.)

Remove unused async keyword

---

cypress/integration/NewLexemeForm.spec.js
cypress/plugins/index.js
index.html
package-lock.json
package.json

Add [cypress-axe](https://www.npmjs.com/package/cypress-axe) cypress-axe as our main CI accesibility testing tool.
Adding instructions on how to run the tests will be tackled on [T302321](https://phabricator.wikimedia.org/T302321)
`tput: No value for $TERM and no -T specified` warning showing in CI is a known bug and still an open issue in cypress.
https://github.com/cypress-io/cypress/issues/15679
Bug: [T307910](https://phabricator.wikimedia.org/T307910)

Add cypress-axe for accessibility testing

---

src/components/ItemLookup.vue
src/components/LanguageInput.vue
src/components/LexicalCategoryInput.vue
src/components/NewLexemeForm.vue
src/store/RootState.ts
src/store/actions.ts
src/store/index.ts
src/store/mutations.ts
tests/integration/NewLexemeForm.test.ts
tests/unit/components/ItemLookup.test.ts
tests/unit/store/actions.test.ts

Change the value prop of the `ItemLookup`, `LanguageInput` and `LexicalCategoryInput` components from a string (item ID) to a full `SearchedItemOption` object, and also change the type in the store, so that we use these objects (with an id, but also a display section) throughout. This will let us populate the lookups from the URL parameters.
Note that ItemLookup doesn’t fully react to incoming changes to the value prop yet, that will come later.
Bug: T308118

Turn store language and lexicalCategory into SearchedItemOption

---

src/components/ItemLookup.vue
tests/unit/components/ItemLookup.test.ts

If the value is changed from outside (e.g. when we load the language or lexical category from URL parameters), it should be shown in the search input as well, and when users click the input, there should be at least one menu item rather than the “no results” message.
Bug: T308118

Make ItemLookup more useful when given non-null value

---

src/store/actions.ts
tests/unit/store/actions.test.ts

Usually, at most one of these will be set to a truthy value: as soon as a language is selected, the spelling variant is cleared, and the input with which the user can change it again is only shown once the language code from the language item is known to not exist. However, when we load parameters from the URL, it is possible to set both at the same time; in this case, the spelling variant should be used over the language code from the language item (assuming the user submits the form without changing the language – otherwise, the spelling variant will be cleared again).
A final fallback to '' is necessary because, unlike the spelling variant, the language code from language item may not be a string; falling back to the empty string matches the previous behavior.
Bug: T298154

Use spelling variant over language code from language item

---

src/components/ItemLookup.vue

Apparently this is necessary to avoid warnings in debug mode:
> ```
> [Vue warn]: Missing required prop: "error"
>   at <ItemLookup label="Lexical category" placeholder="The Lexeme's category, e.g. 'verb'" value=null  ... >
>   at <LexicalCategoryInput modelValue=null onUpdate:modelValue=fn >
>   at <NewLexemeForm>
>   at <App>
> ```
---
Follows-up #177, which was apparently not quite right.

Make ItemLookup error prop optional

---

tests/integration/NewLexemeForm.test.ts

We had two similar tests with the same name (probably one copied from the other and then adjusted without updating the test name). Put them both in a new describe() group, since we’ll want a third test for API submitting soon, and give them extra short names to distinguish them.
Bug: T304511

Fix duplicate NewLexemeForm test case name

---

src/components/NewLexemeForm.vue
src/plugins/MessagesPlugin/DevMessagesRepository.ts
src/plugins/MessagesPlugin/MessageKeys.ts
tests/integration/NewLexemeForm.test.ts

Change the button’s label, and disable it, while the Lexeme is being created. When it’s done, reenable the button and change the label back.
Note that the button may still appear to be enabled when it’s clicked with the mouse (instead of another way to submit the form, like pressing Enter in the lemma input); this requires wmde/wikit#584 to fix.
In the tests, after rejecting the lexemeCreator promise, we apparently need to wait for the next Vue tick six times. I don’t know why, but five isn’t enough. I’m sorry.
Bug: T304511

Change submit button while creating Lexeme

---

src/components/LemmaInput.vue
tests/unit/components/LemmaInput.test.ts

It turns out that this prop in this form is not really suitable.
Follow-up commits will add a more consistent way to get these errors into this component.
This is the first of a series of PRs that split up  #192

Remove unused error prop from LemmaInput

---

src/store/index.ts
tests/integration/NewLexemeForm.test.ts

Most tests need only some minor adjustments to the overall form setup.
That setup is much more obvious if it is the only thing handed to the
createForm function, overriding specific defaults instead of repeating
them.

Reduce redundancy in integration test

---

src/store/actions.ts
tests/unit/store/actions.test.ts

When the user tabs through the form, leaving an item lookup will emit a “value” update for that lookup, even if the value didn’t change. That’s fine for the lexical category lookup, but problematic for the language lookup, because it would wipe whatever spelling variant the user had already entered, and also retry looking up the language code of the item. Instead, only have the `HANDLE_LANGUAGE_CHANGE` action reset the relevant state if the language actually changed, not if it stayed the same. (Note that we still commit the `SET_LANGUAGE` mutation, as the display section of the item may have changed.)
Bug: T201587

Don’t reset spelling variant when language stays the same

---

index.html
src/plugins/MessagesPlugin/DevMessagesRepository.ts

Add a proper message to DevMessagesRepository now that we have the real copy, and hard-code a max length in index.html (100 instead of 1000, so it’s faster to hit by keyboard mashing).
Bug: T308654

Configure lemma length for dev entry point

---

src/store/RootState.ts
src/store/mutations.ts
tests/unit/components/LemmaInput.test.ts

And fix one test that used a wrong message key, to avoid confusion.
---
Noticed while working on #223.

Use MessageKeys type some more

---

src/components/NewLexemeForm.vue
src/components/SpellingVariantInput.vue
src/store/RootState.ts
src/store/actions.ts
src/store/index.ts
src/store/mutations.ts
tests/unit/store/actions.test.ts

Similar to what #223 does for the ItemLookup searchInput, make the SpellingVariantInput searchInput a prop and wire it up with the store. This will let the store show a different error message when the input isn’t empty but hasn’t been selected (not implemented in this commit).
Also, make HANDLE_INIT_PARAMS set the search input when the spelling variant has been loaded from the URL. Previously, the search input was left empty in that case, making it appear as if the spelling variant hadn’t been loaded. With this change, the input is set to just the language code (rather than the language name and code, combined via an interface message) – this should be improved further, but I think that needs a bit more consideration.
Bug: T310134
---
You can test the HANDLE_INIT_PARAMS behavior with …

Make SpellingVariantInput searchInput a prop

---

src/components/ItemLookup.vue
src/components/LanguageInput.vue
src/components/LexicalCategoryInput.vue
src/components/NewLexemeForm.vue
src/store/RootState.ts
src/store/actions.ts
src/store/index.ts
src/store/mutations.ts
tests/unit/components/ItemLookup.test.ts
tests/unit/store/actions.test.ts

Currently implemented only for Lexeme language and lexical category
(spelling variant implementation still pending).
for each field, add a searchInput store value, using which the
component receives the correct error message in the case input
is empty/invalid.
Bug: T310134

export ItemLookup searchInput to be reachable from field components

---

src/store/actions.ts
tests/unit/store/actions.test.ts

for each lookup field, ascertain which type of message key
is required (field empty/entry invalid) and use that while committing
This is a chunk broken down from [PR #223](https://github.com/wmde/new-lexeme-special-page/pull/223)
Bug: T310134

Distinguish between message type for lookup fields

---

.stylelintrc.json
package-lock.json
package.json
src/components/NewLexemeForm.vue
src/components/SpellingVariantInput.vue

This PR is effectively an alternative to #236 
We would have to transform the logical directions in order to support all older browser that we want to support. However, that transformation would also apply to wikit, effectively duplicating itself.

Use backward compatible CSS with literal directions

---

package-lock.json
package.json
src/components/ItemLookup.vue
src/components/LanguageInput.vue
src/components/LexicalCategoryInput.vue
src/components/SpellingVariantInput.vue
tests/unit/components/ItemLookup.test.ts
tests/unit/components/SpellingVariantInput.test.ts

We were already adding it to the lemma input; since Wikit 3.0.0-alpha.7, we can also add it to the other three inputs, which are lookups.
In the `ItemLookup` component, the `aria-required` is passed through as a new prop instead of hard-coded to true – all current item lookups are required, but in principle the component could be used for a non-required item lookup in future.
Note that we use `:aria-required="true"` instead of `aria-required="true"` to pass `true` as a boolean instead of a string.
Bug: T313891

Add aria-required to lookup inputs

---

src/components/ItemLookup.vue
src/components/LanguageInput.vue
src/components/LemmaInput.vue
src/components/LexicalCategoryInput.vue
src/components/RequiredAsterisk.vue
src/components/SpellingVariantInput.vue

The asterisk distances itself from anything else in the suffix slot using the same dimension as the gap between the label and the suffix as a whole; this is needed for the spelling variant input, where the suffix slot also contains a help link.
The asterisk is `aria-hidden` because we already mark the inputs themselves as `aria-required` and people don’t need two indications that the inputs are required.
Bug: T313892

Add asterisk to required form inputs

---

package-lock.json
package.json

Vite 3 requires Node v14.18 or higher, which we don’t have in CI yet.
This reverts commit 8bfc8b5518fb9c0def31f9f94a6578cf8ae53c4e.

Revert "Update vite to version 3.0.1 (#253)"

---

index.html
src/App.vue
src/components/AnonymousEditWarning.vue
src/components/WarningMessage.vue
src/plugins/ConfigPlugin/Config.ts
src/plugins/MessagesPlugin/DevMessagesRepository.ts
src/plugins/MessagesPlugin/MessageKeys.ts
tests/integration/App.test.ts
tests/integration/NewLexemeForm.test.ts
tests/unit/components/AnonymousEditWarning.test.ts
tests/unit/components/__snapshots__/AnonymousEditWarning.test.ts.snap
tests/unit/main.test.ts

Using the standard Wikibase message, but without passing an argument into it. Special:NewLexeme passes the wikibase-entity-lexeme message into it (the argument used to be used as a sort of “your IP address will be visible in the history of the item/property” thing), but that message doesn’t actually exist; the $1 argument is also only used in one remaining translation (vec/Venetian), where I’ve asked the translator to update the translation so it doesn’t use $1 anymore. Once that’s done, I expect we’ll update Wikibase and WikibaseLexeme to also drop this message parameter.
On the dev entry point, the warning can be seen by adding ?isAnonymous=true to the URL.
Bug: T313466

Show warning for anonymous users

---

.stylelintrc.json
src/components/NewLexemeForm.vue
src/components/SearchExisting.vue
src/components/WarningMessage.vue

The linter rule does not allow using 'rem' as a unit,
i've disabled it.
font-size for the copyright message should be 13px, the
rem in this case is relativly calculated from 1rem which is 16px.
margins between elements adapted to represent 16px as well.
The main content wrapper will get a top margin of 0.5rem
so that the gap between search-exiting or anonymous edit message
and the main form always remains 1.5rem.
Bug: T312652

Style adjustments

---

src/components/AnonymousEditWarning.vue
src/components/WarningMessage.vue

they were in the wrong component!
Bug: T312652

Fix anon edit warning message styling

---

index.html
src/components/LanguageInput.vue
src/data-access/DevItemSearcher.ts
src/data-access/LanguageItemSearcher.ts
src/data-access/MwApiItemSearcher.ts
src/init.ts
src/main.ts
src/plugins/ConfigPlugin/Config.ts
src/plugins/ItemSearchPlugin/LanguageItemSearch.ts
tests/integration/App.test.ts
tests/integration/NewLexemeForm.test.ts
tests/unit/data-access/LanguageItemSearcher.test.ts
tests/unit/main.test.ts

Use the language search profile if available

---

package-lock.json
package.json

Per #261 (9e508e9b07), we need to stay on Vite 2 until Wikimedia CI has Node v14.18 or higher.
This reverts commit e758f56a92b0cc3472616d8ef776ce1a6573cefb.
Bug: T314468

Revert "Updat vite related packages (#276)"

---

.github/workflows/comment-deploy-url-to-pr.yaml

This is no longer needed (it grabs the token on its own).

Remove GITHUB_TOKEN from comment-pull-request action

---

src/components/RequiredAsterisk.vue
src/plugins/MessagesPlugin/DevMessagesRepository.ts
src/plugins/MessagesPlugin/MessageKeys.ts

~~This reuses the respective core message for consistency.~~ The core message is not reused, because it is for validation not indicators.
Bug: T322683

Add title message to the required asterisk to make it more legible

---

src/components/NewLexemeForm.vue

This PR removes the italic styling from the license string because it makes it unreadable in non-Latin scripts. If the characters and font do not include italic variants, broken glyphs get rendered, which are particularly difficult to read in cursive scripts like those with Perso-Arabic alphabets. It is especially not a good idea here because the purpose of the NewLexeme page is explicitly multi-lingual.
In some contexts it may make sense to have language specific styles for emphasising text. However, this same string is not italicised elsewhere on Wikidata including the new item page so it is more consistent to not use an emphasised style here.

Do not synthesize italic font in ToS&License copy

---

README.md
package-lock.json
package.json

This addresses the remaining npm related dependabot PRs
Updates vite-plugin-banner, json5 and cypress and explains why we can't update typescript for now.
Bug: T326199

Address remaining npm related pending updates

---

package-lock.json
package.json

`npm install @namics/stylelint-bem stylelint stylelint-config-standard-scss stylelint-config-wikimedia`
Please merge after #415.
Bug: T332576

Update all PostCSS/Stylelint-related dependencies

---

.gitignore
README.md
package-lock.json
package.json

Since Node version was upgraded (see [T314051](https://phabricator.wikimedia.org/T314051) ) and matches minimum requirements, we can upgrade to **Vite 3**.
Bug: [T335735](https://phabricator.wikimedia.org/T335735)

Upgrade to Vite 3

---

.github/workflows/comment-deploy-url-to-pr.yaml

This ocurred due to changes in the package `thollander/actions-comment-pull-request` starting v2.3.1. 
see https://github.com/thollander/actions-comment-pull-request/issues/181 for further details

Add permissions to workflow yaml

---

src/components/LanguageInput.vue
src/components/LemmaInput.vue
src/components/LexicalCategoryInput.vue
src/components/RequiredAsterisk.vue
src/components/SpellingVariantInput.vue

This moves the required marker closer to the actual label to make the connection more obvious. Also it makes it bigger.
The style blocks for overriding the gaps must not be scoped, because it otherwise the styles do not match anything.
The `line-height: 0;` has been added because otherwise the size of the asterisk affects the whole label and thus also the overall layout.
Bug: T322683

Improve the required marker for fields

---

.github/workflows/code-quality.yaml
README.md
package.json

The motivation at the time was apparently that [Fresh][1] only supported up to Node 14, but nowadays it supports up to 20, and 18 is the default. Meanwhile, some CI errors on #519 indicate that dependencies such as @vue/language-core are starting to require syntax like `??=` that’s not available in Node 14. Let’s bump the Node requirement to 16, the version we use in WikibaseLexeme CI.
This reverts commit db8ae7d515916b391d4624b2d5de0b60b14f7d54 (#151).
[1]: https://github.com/wikimedia/fresh
Bug: T348108

Revert "Mostly downgrade required Node version from 16 to 14"

---

package-lock.json
package.json
src/components/LanguageInput.vue
src/components/LemmaInput.vue
src/components/LexicalCategoryInput.vue
src/components/NewLexemeForm.vue
src/components/RequiredAsterisk.vue
src/components/SearchExisting.vue
src/components/SpellingVariantInput.vue

```bash
npm i {stylelint{,-config-{standard-scss,wikimedia}},@namics/stylelint-bem}@latest
```
Most of the changes are made by `npm run fix:stylelint`; removing the now-unused disabling of plugin/stylelint-bem-namics in LanguageInput and LexicalCategoryInput was done manually.
Bug: T348108

Update stylelint-related packages

---

tests/unit/components/LemmaInput.test.ts

The `...config` in particular was causing type issues when upgrading @vue/test-utils in #492; and while that pull request is also blocked for other reasons, I think we can make our lives easier by simplifying these types. Callers of this method (which is local to this one test file) only pass in `props` and/or `global.provide`, so we can just specify the types for those members instead of full `ComponentOptions`; the `Props` type from `LemmaInput` is just duplicated, since I think that’s simpler than trying to get it back out of the full/exported `LemmaInput` type again.
Bug: T348108

Simplify createComponent() types in tests

---

README.md

Based on #512, T341552 and #492.
Bug: T348108

Document more ignored dependencies in README.md

---

package-lock.json
package.json

As far as I can tell, this doesn’t seem to affect the compatibility of the generated code: while the output changes a bit, its size is almost identical; furthermore, the [Vite changelog](https://github.com/vitejs/vite/blob/v4.4.11/packages/vite/CHANGELOG.md) mentions that the nullish coalescing operator isn’t transpiled anymore since Vite 4, but we use such an operator in `actions.ts` and the corresponding build code can be found by searching for `.language.display.label`, and it doesn’t appear to have changed at all – so I think our build config is sufficiently specific that the change to Vite’s defaults doesn’t actually change the target version.
Bug: T348108

Update Vite-related packages

---

src/store/actions.ts
tests/unit/store/actions.test.ts

We now use the property “IETF language tag” for the automatic language code on Wikidata; the subtag of these tags is case-insensitive, but some capitalization is recommended.<sup>[1][1], [2][2]</sup> For MediaWiki or Wikidata, on the other hand, the subtags generally need to be all-lowercase (except our special mis-x-Qid codes, see T317863). Reconcile this by lowercasing all language codes from items in the store action.
[1]: https://en.wikipedia.org/wiki/IETF_language_tag#Syntax_of_language_tags
[2]: https://en.wikipedia.org/w/index.php?title=IETF_language_tag&oldid=1181524280#Syntax_of_language_tags
Bug: T349652

Lowercase language code from item statement

---

package-lock.json
package.json
tests/unit/components/ItemLookup.test.ts

This follows the upgrade of the Vue version shipped with MediaWiki in I0b3b6adf (commit ed6f7b2). The goal is to have those two versions always exactly in sync.
Created with:
`npm install vue@3.3.9 --save-exact`
Bug: T352388

Upgrade Vue from v3.2.27 to v3.3.9

---

README.md

Now that we upgraded from Vue 3.2 to 3.3, TypeScript is no longer *known* to be blocked, so the next round of chores should attempt to upgrade it. If there are any problems, we can add it back to the list.
Whether Vue Test Utils is unblocked is even less clear to me, but let’s still remove it and potentially put it back if needed.
Bug: T352388

Remove TypeScript and Vue Test Utils notes from README.md

---

README.md

I forget about every two months why exactly we cannot upgrade to a newer node version just in the GitHub actions/workflows. Better write that down right where one would expect it.

Add the reason why we cannot update the Node.js version to the README

---

README.md
package-lock.json

Bump versions of @typescript/eslint-plugin and
@typecsript-eslint/parser. Add a note to the README that updates to stylelint-bem past v10 are not possible with current CI setup.
Bug: T354166

Update eslint-related-dependencies and README

---

jest.config.js
src/@types/mediawiki.ts
src/data-access/MwApiLexemeCreator.ts
tests/unit/data-access/MwApiLexemeCreator.test.ts

`mw.util.getUrl()` can return a relative URL, which is illegal to pass directly into `new URL()` unless you also specify the base. Do that.
Directly using `window.location.href` as the base feels a bit ugly, but I don’t think injecting it as a separate parameter of the service would be nicer.
Bug: T358754

Fix redirecting to URL without temporary user

---

index.html
package-lock.json
package.json
vite.config.ts

This sets up Codex components and design tokens so we can start using them. No actual components are migrated to Codex yet.
Components from Wikit can be used directly in our own components. The build is set up so that, when Special:NewLexeme is used within MediaWiki, Codex will be imported from there; this means that our build should get substantially smaller once we don’t need Wikit anymore. In the dev entry point, Codex comes from node_modules/ as expected. (Notice that the styles are only imported in index.html, so they won’t be included in our build output either. As far as I could tell, Vite doesn’t have a CSS equivalent of `external` JS packages in vite.config.ts yet.) When MediaWiki upgrades to a new Codex version, Special:NewLexeme will use the new versions of the Codex components …

Set up Codex

---

src/components/NewLexemeForm.vue
tests/integration/NewLexemeForm.test.ts

A fairly straightforward replacement – we just have to rename a few props and update one selector.
The button’s size changes ever so slightly; IMHO the Codex version looks a tad nicer anyway.
Bug: T370052

Use Codex button instead of Wikit button

---

src/components/ErrorMessage.vue
src/components/WarningMessage.vue
tests/unit/components/__snapshots__/AnonymousEditWarning.test.ts.snap

Replace instances of Wikit's Message component in ErrorMessage and WarningMessage with the Codex equivalent.
Bug: T370055

Replace Wikit Message with Codex Message component

---

src/components/LemmaInput.vue
tests/integration/NewLexemeForm.test.ts
tests/unit/components/LemmaInput.test.ts

Change the lemma to not use Wikit anymore. In Codex, this corresponds to two components, so use both.
The spacing of the “required” asterisk is done differently – it’s no longer in a flex container, so establish the spacing using margin instead. The asterisk is now also part of the actual <label> element, which isn’t ideal but I think can’t be avoided within Codex. (Note that Codex doesn’t want us to indicate required fields at all; see also T374432.)
Bug: T370054
----
The second commit is optional, if you don’t like it I can take it out again:
----
Restructure error computation
Since Codex wants the status and messages as separate props, but we compute them at the same time, let’s have the computed return an object with both props.

Use Codex Field + TextInput instead of Wikit TextInput

---

src/components/SpellingVariantInput.vue

Replaces the Wikit Link component with a plain link, which gets codex styling through the default stylesheet.
Bug: T370053

Remove wikit link component

---

cypress/e2e/NewLexemeForm.cy.js
src/components/NewLexemeForm.vue
tests/integration/NewLexemeForm.test.ts

Putting the event handler on the button seems more intuitive to me, and works around T376622 (a Codex button doesn’t submit the form when activated using the keyboard). Note that a “click” handler on a button also fires when it’s activated using the keyboard (this is standard browser behavior but still works on a Codex button).
As far as I’m aware, there was no special reason to have the event handler on the form before – the event handler was added in e35cdf36d1, replacing a different attribute on the `<form>`, so it probably just seemed natural to put the event handler on the `<form>` at the time.
Bug: T370052
Bug: T376622

Submit form using click handler

---

src/components/AnonymousEditWarning.vue
src/components/LanguageInput.vue
src/components/LemmaInput.vue
src/components/LexicalCategoryInput.vue
src/components/NewLexemeForm.vue
src/components/RequiredAsterisk.vue
src/components/SearchExisting.vue
src/components/SpellingVariantInput.vue
src/styles/custom-variables.css

Migrate away from Wikit tokens to Codex SASS variables where they are available. In some cases we use custom CSS variables for values from Wikit whose Codex equivalents are missing.
Bug: [T369510](https://phabricator.wikimedia.org/T369510)
Bug: [T369508](https://phabricator.wikimedia.org/T369508)
Bug: [T369509](https://phabricator.wikimedia.org/T369509)

Use Codex tokens and custom spacing variables

---

.github/dependabot.yml
package-lock.json
package.json

See individual commit messages. (Reverts #774.)

Fix Vue version

---

cypress/e2e/NewLexemeForm.cy.js
package-lock.json
package.json
src/components/ItemLookup.vue
src/components/LanguageInput.vue
src/components/NewLexemeForm.vue
src/components/SpellingVariantInput.vue
tests/integration/NewLexemeForm.test.ts
tests/unit/components/ItemLookup.test.ts
tests/unit/components/SpellingVariantInput.test.ts

Depends on changes to Codex: [T376024](https://phabricator.wikimedia.org/T376024) ([Iddbd4a83a444b382d0b9318cd1831b42126464c4](https://gerrit.wikimedia.org/r/q/Iddbd4a83a444b382d0b9318cd1831b42126464c4))
Replace usages of Wikit's Lookup compontent in `ItemLookup` and `SpellingVariantInput` with the `CdxLookup` component.
Bug: T370057

Replace Wikit Lookup component with Codex

---

src/components/SpellingVariantInput.vue
tests/unit/components/SpellingVariantInput.test.ts

In the port from Wikit to Codex, the new implementation of `SpellingVariantInput` was working, but was dropping some inputs entered by users.
Remove the unused `search-input` attribute of the Codex Lookup component in `SpellingVariantInput` and wire the `input-value` property in the same way it has been connected in the `ItemLookup` implementation.
Bug: T379595

Fix unreliable input on SpellingVariantInput

---

src/components/SpellingVariantInput.vue
tests/unit/components/SpellingVariantInput.test.ts

The code for `SpellingVariantInput` was making an unnecessary extra call to `onOptionSelected` when `onInput` was called, to satisfy assertions in the unit test suite that are very involved with the internals of the component eventing logic. This worked okay for codex 1.14.0, but is incompatible with the behaviour changes introduced in Icd4b7ed1e34bf5b2d62f705fdd8c6f4e0cf088d1.
Remove the unnecessary call, and remove the unnecessarily detailed unit tests.
Bug: T379595

Remove unnecessary `onOptionSelected` call

---

src/components/NewLexemeForm.vue

SASS has been emitting a deprecation warning because of a coming change in SASS behaviour:
https://sass-lang.com/documentation/breaking-changes/mixed-decls/
In `NewLexemeForm.vue` we were using the `&` parent selector before applying additional properties to the `.wbl-snl-form` element.
In this specific case, moving the parent selector after the property declarations has no effect on the semantics of the SASS or the generated CSS, and resolves the deprecation warning.
Bug: T372250

Move properties before nested selector to resolve deprecation warnings

---

src/components/LanguageInput.vue
src/components/LemmaInput.vue
src/components/LexicalCategoryInput.vue
src/components/NewLexemeForm.vue
src/components/RequiredAsterisk.vue
src/components/SpellingVariantInput.vue
vite.config.ts

Now that the migration to Vue 3 is complete, compatConfig is no longer needed and should be removed.
Bug: T355239

Remove unnecessary compatConfig flags

---

package-lock.json
package.json
src/components/LanguageInput.vue
src/components/LexicalCategoryInput.vue
src/components/NewLexemeForm.vue
src/components/RequiredAsterisk.vue
src/components/SearchExisting.vue
src/components/SpellingVariantInput.vue

`npm install sass@1.83.4`
Bug: T382330

Chore: Update sass, migrate from @import to @use

---

package-lock.json
package.json
tests/unit/components/SpellingVariantInput.test.ts
tests/unit/components/__snapshots__/AnonymousEditWarning.test.ts.snap

I needed to use `--legacy-peer-deps` here as npm seemingly doesn't allow installing/ updating a package and its peer dependencies (@wikimedia/codex which has a peer dependency on vue, thus they would need to be updated in a single transaction). This seems to be desired behaviour, per: npm/cli#7719 (comment)
`npm install --legacy-peer-deps vue@3.5.13 vue-tsc@2.2.0 vuex@4.1.0 @wikimedia/codex@1.20.0 @wikimedia/codex-design-tokens@1.20.0 @vue/server-renderer@3.5.13`
Also some, seemingly harmless, changes in tests where needed. 
Bug: T382330

Update Vue, Codex and related dependencies
